version: '2'
services:
 elastic-search:
  image: elasticsearch:latest
  ports:
  - "80:80"
  - "9200:9200"
  - "9300:9300"
  volumes:
  - ./data/logstash-data/:/etc/logstash
  command: elasticsearch -Des.network.host=0.0.0.0
